import { gql } from 'graphql-tag';

const kits = gql`
  enum KitType {
    Admin
    Customer
  }

  type Kit implements Node {
    id: ID!
    createdAt: DateTime!
    updatedAt: DateTime!
    type: KitType!
    languageCode: LanguageCode!
    name: String!
    slug: String!
    description: String!
    enabled: Boolean!
    featuredAsset: Asset
    assets: [Asset!]!
    "Returns all KitVariants"
    variants: [KitVariant!]!
    "Returns a paginated, sortable, filterable list of KitVariants"
    variantList(options: KitVariantListOptions): KitVariantList!
    facetValues: [FacetValue!]!
    translations: [KitTranslation!]!
    collections: [Collection!]!
    channels: [Channel!]!
    # discount: Float
    # price: Money!
    # priceWithTax: Money!
    # discountedPriceWithTax: Money!
  }

  type KitVariant implements Node {
    id: ID!
    kit: Kit!
    kitId: ID!
    quantity: Int!
    discount: Float
    createdAt: DateTime!
    updatedAt: DateTime!
    productVariantId: ID!
    productVariant: ProductVariant!
  }

  type KitTranslation {
    id: ID!
    createdAt: DateTime!
    updatedAt: DateTime!
    languageCode: LanguageCode!
    name: String!
    slug: String!
    description: String!
  }
`;

const kitInputs = gql`
  input KitFilterParameter {
    facetValueId: IDOperators
    sku: StringOperators
  }

  # generated by generateListOptions function
  input KitListOptions
  input KitVariantListOptions

  input KitTranslationInput {
    languageCode: LanguageCode!
    name: String!
    slug: String!
    description: String!
  }

  input CreateKitInput {
    featuredAssetId: ID
    enabled: Boolean
    assetIds: [ID!]
    facetValueIds: [ID!]
    translations: [KitTranslationInput!]!
  }

  input UpdateKitInput {
    id: ID!
    enabled: Boolean
    featuredAssetId: ID
    assetIds: [ID!]
    facetValueIds: [ID!]
    translations: [KitTranslationInput!]
  }

  input AssignKitsToChannelInput {
    kitIds: [ID!]!
    channelId: ID!
    priceFactor: Float
  }

  input RemoveKitsFromChannelInput {
    kitIds: [ID!]!
    channelId: ID!
  }

  input CreateKitVariantInput {
    kitId: ID
    productVariantId: ID
    quantity: Int
    discount: Float
  }

  input UpdateKitVariantInput {
    id: ID!
    productVariantId: ID
    quantity: Int
    discount: Float
  }
`;

const adminApiExtensions = gql`
  ${kitInputs}
  ${kits}

  type KitList implements PaginatedList {
    items: [Kit!]!
    totalItems: Int!
  }

  type KitVariantList implements PaginatedList {
    items: [KitVariant!]!
    totalItems: Int!
  }

  extend type Query {
    kit(id: ID, slug: String): Kit
    kits(options: KitListOptions): KitList!

    kitVariants(options: KitVariantListOptions, kitId: ID): KitVariantList!
    "Get a KitVariant by id"
    kitVariant(id: ID!): KitVariant
  }

  extend type Mutation {
    "Create a new Kit"
    createKit(input: CreateKitInput!): Kit!

    "Update an existing Kit"
    updateKit(input: UpdateKitInput!): Kit!

    "Update multiple existing Kits"
    updateKits(input: [UpdateKitInput!]!): [Kit!]!

    "Delete a Kit"
    deleteKit(id: ID!): DeletionResponse!

    "Delete multiple Kits"
    deleteKits(ids: [ID!]!): [DeletionResponse!]!

    "Assigns all KitVariants of Kit to the specified Channel"
    assignKitsToChannel(input: AssignKitsToChannelInput!): [Kit!]!

    "Removes all KitVariants of Kit from the specified Channel"
    removeKitsFromChannel(input: RemoveKitsFromChannelInput!): [Kit!]!

    "Create a set of KitVariants based on the OptionGroups assigned to the given Kit"
    createKitVariants(input: [CreateKitVariantInput!]!): [KitVariant]!

    createKitVariant(input: CreateKitVariantInput!): KitVariant!

    "Update a set of KitVariants based on the OptionGroups assigned to the given Kit"
    updateKitVariants(input: [UpdateKitVariantInput!]!): [KitVariant]!

    "Update a KitVariant"
    updateKitVariant(input: UpdateKitVariantInput!): KitVariant!

    "Delete a KitVariant"
    deleteKitVariant(id: ID!): DeletionResponse!

    "Delete multiple KitVariants"
    deleteKitVariants(ids: [ID!]!): [DeletionResponse!]!
  }
`;

export { adminApiExtensions };
