import {MigrationInterface, QueryRunner} from "typeorm";

export class ExternalSync1778944641272 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `sync_table` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `tableName` varchar(255) NOT NULL, `lastSyncedAt` datetime NULL, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_733da27f02af25337f3e1b1531` (`tableName`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` ADD `customFieldsPagecontent` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` ADD `customFieldsRichcontent` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` ADD `customFieldsFaqs` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` ADD `customFieldsSeometadata` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` ADD `customFieldsSemanticknowledge` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD `customFieldsCategorytype` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD `customFieldsGlobalmetadata` json NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` ADD `customFieldsSeo_metadata` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` ADD `customFieldsLlm_metadata` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` ADD `customFieldsMaterial` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsMain_sku` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD UNIQUE INDEX `IDX_6d81657fc7cbcf605b9c34746f` (`customFieldsMain_sku`)", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsSku_mba` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD UNIQUE INDEX `IDX_6ebe41f78d17535d5e6198d92f` (`customFieldsSku_mba`)", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsGrouped_child_skus` text NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsExternal_product_type` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsIs_printable` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsPrintings` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsMeasurements` json NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsPackaging` longtext NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD `customFieldsDigital_assets` json NULL", undefined);
        await queryRunner.query("ALTER TABLE `asset` ADD `customFieldsExternal_id` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `asset` ADD UNIQUE INDEX `IDX_dbfa8d6e10bc23b5399448222b` (`customFieldsExternal_id`)", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsItem_code` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsEan_code` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsBarcode` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsHs_code` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIntrastat_code` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_new` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_best_seller` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_stockoff` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsDate_release` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsDate_new_end` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_promotion` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsPromotion_value` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsPromotion_percentage` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsPromotion_date_start` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsPromotion_date_end` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_featured` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsDate_featured_start` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsDate_featured_end` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsIs_discontinued` tinyint NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsDate_discontinued` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_stocks_1` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_date_1` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_stocks_2` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_date_2` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_stocks_3` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` ADD `customFieldsNext_date_3` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsMappingid` int NULL DEFAULT '0'", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsNr_entidade` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsEmpresa` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsNif` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsEstabelecimento` int NULL DEFAULT '0'", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsTelemovel` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsTipo` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsSegmento` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsAcesso_web` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsNr_tipo_reg` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsSite_associado` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsIs_active` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsId_vendedor` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsDesc_cliente` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsDesc_prodint` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsDesc_imp` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsCond_pagamento` varchar(255) NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsMax_dias_credito` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsPlafond_credito` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsSaldo_em_aberto` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsOnline_last_indexed_status` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD `customFieldsOnline_last_indexed_at_date` datetime(6) NULL", undefined);
        await queryRunner.query("ALTER TABLE `channel` ADD `customFieldsNobrinde_channel_id` int NULL", undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `channel` DROP COLUMN `customFieldsNobrinde_channel_id`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsOnline_last_indexed_at_date`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsOnline_last_indexed_status`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsSaldo_em_aberto`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsPlafond_credito`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsMax_dias_credito`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsCond_pagamento`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsDesc_imp`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsDesc_prodint`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsDesc_cliente`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsId_vendedor`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsIs_active`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsSite_associado`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsNr_tipo_reg`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsAcesso_web`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsSegmento`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsTipo`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsTelemovel`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsEstabelecimento`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsNif`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsEmpresa`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsNr_entidade`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP COLUMN `customFieldsMappingid`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_date_3`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_stocks_3`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_date_2`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_stocks_2`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_date_1`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsNext_stocks_1`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsDate_discontinued`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_discontinued`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsDate_featured_end`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsDate_featured_start`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_featured`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsPromotion_date_end`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsPromotion_date_start`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsPromotion_percentage`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsPromotion_value`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_promotion`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsDate_new_end`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsDate_release`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_stockoff`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_best_seller`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIs_new`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsIntrastat_code`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsHs_code`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsBarcode`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsEan_code`", undefined);
        await queryRunner.query("ALTER TABLE `product_variant` DROP COLUMN `customFieldsItem_code`", undefined);
        await queryRunner.query("ALTER TABLE `asset` DROP INDEX `IDX_dbfa8d6e10bc23b5399448222b`", undefined);
        await queryRunner.query("ALTER TABLE `asset` DROP COLUMN `customFieldsExternal_id`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsDigital_assets`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsPackaging`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsMeasurements`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsPrintings`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsIs_printable`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsExternal_product_type`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsGrouped_child_skus`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP INDEX `IDX_6ebe41f78d17535d5e6198d92f`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsSku_mba`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP INDEX `IDX_6d81657fc7cbcf605b9c34746f`", undefined);
        await queryRunner.query("ALTER TABLE `product` DROP COLUMN `customFieldsMain_sku`", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` DROP COLUMN `customFieldsMaterial`", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` DROP COLUMN `customFieldsLlm_metadata`", undefined);
        await queryRunner.query("ALTER TABLE `product_translation` DROP COLUMN `customFieldsSeo_metadata`", undefined);
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `customFieldsGlobalmetadata`", undefined);
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `customFieldsCategorytype`", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` DROP COLUMN `customFieldsSemanticknowledge`", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` DROP COLUMN `customFieldsSeometadata`", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` DROP COLUMN `customFieldsFaqs`", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` DROP COLUMN `customFieldsRichcontent`", undefined);
        await queryRunner.query("ALTER TABLE `collection_translation` DROP COLUMN `customFieldsPagecontent`", undefined);
        await queryRunner.query("DROP INDEX `IDX_733da27f02af25337f3e1b1531` ON `sync_table`", undefined);
        await queryRunner.query("DROP TABLE `sync_table`", undefined);
   }

}
