import {MigrationInterface, QueryRunner} from "typeorm";

export class NobrindeEntity1778942160041 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `nobrinde_budget` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id_phc` int NOT NULL, `id_site` int NULL, `nr_doc_pv` int NULL, `data_documento` varchar(50) NULL, `tipo_reg` int NULL, `serie` varchar(50) NULL, `nr_entidade` int NULL, `estabelecimento` int NULL, `empresa` varchar(64) NULL, `morada` varchar(50) NULL, `localidade` varchar(50) NULL, `c_postal` varchar(50) NULL, `nif` varchar(50) NULL, `cond_pagamento` varchar(255) NULL, `morada_entrega` varchar(50) NULL, `data_expedicao` varchar(50) NULL, `total_liq` varchar(50) NULL, `iva` double NULL, `taxa_iva` double NULL, `total` double NULL, `observacoes` varchar(255) NULL, `sigla_comercial` varchar(50) NULL, `desc_comercial` varchar(7) NULL, `tracking` varchar(1) NULL, `pdfAssetId` varchar(36) NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `nobrinde_budget_line` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id_phc` int NOT NULL, `id_linhas` varchar(50) NULL, `ordem` int NULL, `referencia_externa` varchar(50) NULL, `referencia` varchar(50) NULL, `nome_produto` varchar(64) NULL, `qtdd` int NULL, `preco_unit` double NULL, `desc` double NULL, `preco_unit_desc` double NULL, `total` double NULL, `iva` double NULL, `id` varchar(36) NOT NULL, `budgetId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `nobrinde_channel` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `channel_type` varchar(20) NOT NULL, `config_json` text NULL, `created_by` varchar(100) NULL, `date_created` datetime NOT NULL, `date_updated` datetime NOT NULL, `is_active` tinyint NOT NULL, `name` varchar(100) NOT NULL, `slug` varchar(100) NOT NULL, `updated_by` varchar(100) NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `nobrinde_order` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id_phc` int NOT NULL, `id_site` varchar(50) NULL, `nr_doc_pv` int NULL, `data_documento` varchar(50) NULL, `tipo_reg` int NULL, `serie` varchar(50) NULL, `nr_entidade` int NULL, `estabelecimento` int NULL, `empresa` varchar(64) NULL, `morada` varchar(64) NULL, `localidade` varchar(50) NULL, `c_postal` varchar(50) NULL, `nif` varchar(50) NULL, `cond_pagamento` varchar(50) NULL, `morada_entrega` varchar(64) NULL, `data_expedicao` varchar(50) NULL, `total_liq` double NULL, `iva` double NULL, `taxa_iva` double NULL, `total` double NULL, `observacoes` text NULL, `sigla_comercial` text NULL, `desc_comercial` double NULL, `tracking` varchar(50) NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `nobrinde_order_line` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id_phc` int NOT NULL, `id_linhas` varchar(50) NULL, `ordem` int NULL, `referencia_externa` varchar(50) NULL, `referencia` varchar(50) NULL, `nome_produto` varchar(64) NULL, `qtdd` int NULL, `preco_unit` double NULL, `desc` double NULL, `preco_unit_desc` int NULL, `total` double NULL, `iva` double NULL, `estado` varchar(50) NULL, `id` varchar(36) NOT NULL, `orderId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `nobrinde_sale_user` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id_vendedor` int NOT NULL, `sigla` varchar(10) NULL, `nome` varchar(100) NULL, `telefone` varchar(50) NULL, `telemovel` varchar(50) NULL, `email` varchar(100) NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `nobrinde_budget_line` ADD CONSTRAINT `FK_c2f9bf1cc4f4948c7a9b321ef41` FOREIGN KEY (`budgetId`) REFERENCES `nobrinde_budget`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `nobrinde_order_line` ADD CONSTRAINT `FK_9924a26b9e258cf31d37455152b` FOREIGN KEY (`orderId`) REFERENCES `nobrinde_order`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `nobrinde_order_line` DROP FOREIGN KEY `FK_9924a26b9e258cf31d37455152b`", undefined);
        await queryRunner.query("ALTER TABLE `nobrinde_budget_line` DROP FOREIGN KEY `FK_c2f9bf1cc4f4948c7a9b321ef41`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_sale_user`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_order_line`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_order`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_channel`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_budget_line`", undefined);
        await queryRunner.query("DROP TABLE `nobrinde_budget`", undefined);
   }

}
