import {MigrationInterface, QueryRunner} from "typeorm";

export class CmsPlugin1778943041567 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `payload_faq_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(1024) NOT NULL, `items` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_aa9a532bc59abd344cc0384b32` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_faq` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_0fa62116e26c6f940b9b84fc23` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_document_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(1024) NOT NULL, `items` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_408a04bf3650f8881e3ef0e491` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_document` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_44be831306fca0206c4100be21` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_banner_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(1024) NOT NULL, `items` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_31168764efeebfbc548f36a7c5` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_banner` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_c8d3ad5922da044ea3dedf6e5a` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_alert_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(1024) NOT NULL, `content` text NOT NULL, `targetUrls` json NULL, `button` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_fc564aad49ec6a6017d53f8d23` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_alert` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, `assetId` varchar(255) NULL, UNIQUE INDEX `IDX_b9287046fbd7dd1988f2b1b6ee` (`code`), INDEX `IDX_54abda8eabc14ed1c03ea93b14` (`assetId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_page_block_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `columns` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_761ff10fcefadc44d47f5cdead` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_page_block` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `pageId` varchar(36) NOT NULL, `code` varchar(255) NULL, `index` int NOT NULL DEFAULT '0', `active` tinyint NOT NULL DEFAULT 1, `css` json NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_page` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `title` varchar(255) NOT NULL, `slug` varchar(500) NULL, `active` tinyint NOT NULL DEFAULT 1, `seo` json NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_news_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(255) NULL, `description` text NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_4e409ad46c6a1a22c2ed659f10` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_author_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `title` varchar(255) NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_8210e9ea820cf46d548392930b` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_author` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `logo` varchar(500) NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_85291b6b74fc27c1f5f145301f` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_category` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `description` varchar(500) NULL, `type` varchar(50) NOT NULL, `active` tinyint NOT NULL DEFAULT 1, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_7dd7a9ad57f2e3b60482f7e7f6` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_news` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `src` varchar(500) NULL, `authorId` varchar(36) NULL, `relatedNewsIds` text NULL, `seo` json NULL, `categoryId` varchar(36) NULL, `id` varchar(36) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_footer_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `navLinks` json NULL, `socialLinks` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_c242286c5d7efe0fd5ab235fc9` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_footer` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_f97f617d406891e196f6ffa873` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_header_translation` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `languageCode` varchar(255) NOT NULL, `navLinks` json NULL, `id` varchar(36) NOT NULL, `baseId` varchar(36) NULL, INDEX `IDX_fbfbba8b92b625313db5be7116` (`baseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_header` (`createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `code` varchar(255) NOT NULL, `logo` varchar(500) NULL, `id` varchar(36) NOT NULL, UNIQUE INDEX `IDX_1d6662206dad535369160daf8f` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_faq_channels_channel` (`payloadFaqId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_326f1bf1e92331c97f1c42ff39` (`payloadFaqId`), INDEX `IDX_c6cdc1a4fb380731abe5f6802c` (`channelId`), PRIMARY KEY (`payloadFaqId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_document_channels_channel` (`payloadDocumentId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_d9b5cb9a6a8dfd2f1a34dd45cb` (`payloadDocumentId`), INDEX `IDX_b642d94f965e09d9411d3c8295` (`channelId`), PRIMARY KEY (`payloadDocumentId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_banner_channels_channel` (`payloadBannerId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_35d3f295523cc2f879f533387f` (`payloadBannerId`), INDEX `IDX_58d421ecd181f6ece23e7d676b` (`channelId`), PRIMARY KEY (`payloadBannerId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_alert_channels_channel` (`payloadAlertId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_8c635dd7568b752dae0fd1a49d` (`payloadAlertId`), INDEX `IDX_3fe3cef26433b7827c7f3c5974` (`channelId`), PRIMARY KEY (`payloadAlertId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_page_channels_channel` (`payloadPageId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_b3bbc848ef0ab6a59d57793fda` (`payloadPageId`), INDEX `IDX_6e87308875d21ed2b76baf0c2f` (`channelId`), PRIMARY KEY (`payloadPageId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_author_channels_channel` (`payloadAuthorId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_fcdc26367b4c6fa7f61a98a814` (`payloadAuthorId`), INDEX `IDX_368c961a32ec604103a99db0c5` (`channelId`), PRIMARY KEY (`payloadAuthorId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_category_channels_channel` (`payloadCategoryId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_e3b4ccebf99452d9506bbb3438` (`payloadCategoryId`), INDEX `IDX_aeac0260f24c9356c440ec37dc` (`channelId`), PRIMARY KEY (`payloadCategoryId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_news_channels_channel` (`payloadNewsId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_04373df796d8c869634fda42bf` (`payloadNewsId`), INDEX `IDX_12e1aaa13157852ec040d44fec` (`channelId`), PRIMARY KEY (`payloadNewsId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_footer_channels_channel` (`payloadFooterId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_b4bc21a5b982be6ea4316da69f` (`payloadFooterId`), INDEX `IDX_44e10582d0695d751dd8863af3` (`channelId`), PRIMARY KEY (`payloadFooterId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `payload_header_channels_channel` (`payloadHeaderId` varchar(36) NOT NULL, `channelId` varchar(36) NOT NULL, INDEX `IDX_b2054782f5d5e41f036c6d047d` (`payloadHeaderId`), INDEX `IDX_2d484e641fd19ccce2237d6c38` (`channelId`), PRIMARY KEY (`payloadHeaderId`, `channelId`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_translation` ADD CONSTRAINT `FK_aa9a532bc59abd344cc0384b324` FOREIGN KEY (`baseId`) REFERENCES `payload_faq`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_translation` ADD CONSTRAINT `FK_408a04bf3650f8881e3ef0e4917` FOREIGN KEY (`baseId`) REFERENCES `payload_document`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_translation` ADD CONSTRAINT `FK_31168764efeebfbc548f36a7c50` FOREIGN KEY (`baseId`) REFERENCES `payload_banner`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_translation` ADD CONSTRAINT `FK_fc564aad49ec6a6017d53f8d236` FOREIGN KEY (`baseId`) REFERENCES `payload_alert`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert` ADD CONSTRAINT `FK_54abda8eabc14ed1c03ea93b14c` FOREIGN KEY (`assetId`) REFERENCES `asset`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_block_translation` ADD CONSTRAINT `FK_761ff10fcefadc44d47f5cdead6` FOREIGN KEY (`baseId`) REFERENCES `payload_page_block`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_block` ADD CONSTRAINT `FK_8363310eebe14a4d2fef996b86f` FOREIGN KEY (`pageId`) REFERENCES `payload_page`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_translation` ADD CONSTRAINT `FK_4e409ad46c6a1a22c2ed659f103` FOREIGN KEY (`baseId`) REFERENCES `payload_news`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_translation` ADD CONSTRAINT `FK_8210e9ea820cf46d548392930b4` FOREIGN KEY (`baseId`) REFERENCES `payload_author`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_news` ADD CONSTRAINT `FK_2e8d550f768e7f887416332fa2f` FOREIGN KEY (`authorId`) REFERENCES `payload_author`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_news` ADD CONSTRAINT `FK_9d0e049755d8112752eea114d2f` FOREIGN KEY (`categoryId`) REFERENCES `payload_category`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_translation` ADD CONSTRAINT `FK_c242286c5d7efe0fd5ab235fc93` FOREIGN KEY (`baseId`) REFERENCES `payload_footer`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_header_translation` ADD CONSTRAINT `FK_fbfbba8b92b625313db5be71163` FOREIGN KEY (`baseId`) REFERENCES `payload_header`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_channels_channel` ADD CONSTRAINT `FK_326f1bf1e92331c97f1c42ff397` FOREIGN KEY (`payloadFaqId`) REFERENCES `payload_faq`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_channels_channel` ADD CONSTRAINT `FK_c6cdc1a4fb380731abe5f6802ce` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_channels_channel` ADD CONSTRAINT `FK_d9b5cb9a6a8dfd2f1a34dd45cb2` FOREIGN KEY (`payloadDocumentId`) REFERENCES `payload_document`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_channels_channel` ADD CONSTRAINT `FK_b642d94f965e09d9411d3c8295d` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_channels_channel` ADD CONSTRAINT `FK_35d3f295523cc2f879f533387fd` FOREIGN KEY (`payloadBannerId`) REFERENCES `payload_banner`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_channels_channel` ADD CONSTRAINT `FK_58d421ecd181f6ece23e7d676ba` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_channels_channel` ADD CONSTRAINT `FK_8c635dd7568b752dae0fd1a49d2` FOREIGN KEY (`payloadAlertId`) REFERENCES `payload_alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_channels_channel` ADD CONSTRAINT `FK_3fe3cef26433b7827c7f3c59749` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_channels_channel` ADD CONSTRAINT `FK_b3bbc848ef0ab6a59d57793fda0` FOREIGN KEY (`payloadPageId`) REFERENCES `payload_page`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_channels_channel` ADD CONSTRAINT `FK_6e87308875d21ed2b76baf0c2ff` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_channels_channel` ADD CONSTRAINT `FK_fcdc26367b4c6fa7f61a98a8146` FOREIGN KEY (`payloadAuthorId`) REFERENCES `payload_author`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_channels_channel` ADD CONSTRAINT `FK_368c961a32ec604103a99db0c50` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_category_channels_channel` ADD CONSTRAINT `FK_e3b4ccebf99452d9506bbb3438e` FOREIGN KEY (`payloadCategoryId`) REFERENCES `payload_category`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_category_channels_channel` ADD CONSTRAINT `FK_aeac0260f24c9356c440ec37dc1` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_channels_channel` ADD CONSTRAINT `FK_04373df796d8c869634fda42bfa` FOREIGN KEY (`payloadNewsId`) REFERENCES `payload_news`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_channels_channel` ADD CONSTRAINT `FK_12e1aaa13157852ec040d44fecc` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_channels_channel` ADD CONSTRAINT `FK_b4bc21a5b982be6ea4316da69fe` FOREIGN KEY (`payloadFooterId`) REFERENCES `payload_footer`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_channels_channel` ADD CONSTRAINT `FK_44e10582d0695d751dd8863af30` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_header_channels_channel` ADD CONSTRAINT `FK_b2054782f5d5e41f036c6d047d7` FOREIGN KEY (`payloadHeaderId`) REFERENCES `payload_header`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
        await queryRunner.query("ALTER TABLE `payload_header_channels_channel` ADD CONSTRAINT `FK_2d484e641fd19ccce2237d6c38a` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE", undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `payload_header_channels_channel` DROP FOREIGN KEY `FK_2d484e641fd19ccce2237d6c38a`", undefined);
        await queryRunner.query("ALTER TABLE `payload_header_channels_channel` DROP FOREIGN KEY `FK_b2054782f5d5e41f036c6d047d7`", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_channels_channel` DROP FOREIGN KEY `FK_44e10582d0695d751dd8863af30`", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_channels_channel` DROP FOREIGN KEY `FK_b4bc21a5b982be6ea4316da69fe`", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_channels_channel` DROP FOREIGN KEY `FK_12e1aaa13157852ec040d44fecc`", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_channels_channel` DROP FOREIGN KEY `FK_04373df796d8c869634fda42bfa`", undefined);
        await queryRunner.query("ALTER TABLE `payload_category_channels_channel` DROP FOREIGN KEY `FK_aeac0260f24c9356c440ec37dc1`", undefined);
        await queryRunner.query("ALTER TABLE `payload_category_channels_channel` DROP FOREIGN KEY `FK_e3b4ccebf99452d9506bbb3438e`", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_channels_channel` DROP FOREIGN KEY `FK_368c961a32ec604103a99db0c50`", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_channels_channel` DROP FOREIGN KEY `FK_fcdc26367b4c6fa7f61a98a8146`", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_channels_channel` DROP FOREIGN KEY `FK_6e87308875d21ed2b76baf0c2ff`", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_channels_channel` DROP FOREIGN KEY `FK_b3bbc848ef0ab6a59d57793fda0`", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_channels_channel` DROP FOREIGN KEY `FK_3fe3cef26433b7827c7f3c59749`", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_channels_channel` DROP FOREIGN KEY `FK_8c635dd7568b752dae0fd1a49d2`", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_channels_channel` DROP FOREIGN KEY `FK_58d421ecd181f6ece23e7d676ba`", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_channels_channel` DROP FOREIGN KEY `FK_35d3f295523cc2f879f533387fd`", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_channels_channel` DROP FOREIGN KEY `FK_b642d94f965e09d9411d3c8295d`", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_channels_channel` DROP FOREIGN KEY `FK_d9b5cb9a6a8dfd2f1a34dd45cb2`", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_channels_channel` DROP FOREIGN KEY `FK_c6cdc1a4fb380731abe5f6802ce`", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_channels_channel` DROP FOREIGN KEY `FK_326f1bf1e92331c97f1c42ff397`", undefined);
        await queryRunner.query("ALTER TABLE `payload_header_translation` DROP FOREIGN KEY `FK_fbfbba8b92b625313db5be71163`", undefined);
        await queryRunner.query("ALTER TABLE `payload_footer_translation` DROP FOREIGN KEY `FK_c242286c5d7efe0fd5ab235fc93`", undefined);
        await queryRunner.query("ALTER TABLE `payload_news` DROP FOREIGN KEY `FK_9d0e049755d8112752eea114d2f`", undefined);
        await queryRunner.query("ALTER TABLE `payload_news` DROP FOREIGN KEY `FK_2e8d550f768e7f887416332fa2f`", undefined);
        await queryRunner.query("ALTER TABLE `payload_author_translation` DROP FOREIGN KEY `FK_8210e9ea820cf46d548392930b4`", undefined);
        await queryRunner.query("ALTER TABLE `payload_news_translation` DROP FOREIGN KEY `FK_4e409ad46c6a1a22c2ed659f103`", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_block` DROP FOREIGN KEY `FK_8363310eebe14a4d2fef996b86f`", undefined);
        await queryRunner.query("ALTER TABLE `payload_page_block_translation` DROP FOREIGN KEY `FK_761ff10fcefadc44d47f5cdead6`", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert` DROP FOREIGN KEY `FK_54abda8eabc14ed1c03ea93b14c`", undefined);
        await queryRunner.query("ALTER TABLE `payload_alert_translation` DROP FOREIGN KEY `FK_fc564aad49ec6a6017d53f8d236`", undefined);
        await queryRunner.query("ALTER TABLE `payload_banner_translation` DROP FOREIGN KEY `FK_31168764efeebfbc548f36a7c50`", undefined);
        await queryRunner.query("ALTER TABLE `payload_document_translation` DROP FOREIGN KEY `FK_408a04bf3650f8881e3ef0e4917`", undefined);
        await queryRunner.query("ALTER TABLE `payload_faq_translation` DROP FOREIGN KEY `FK_aa9a532bc59abd344cc0384b324`", undefined);
        await queryRunner.query("DROP INDEX `IDX_2d484e641fd19ccce2237d6c38` ON `payload_header_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b2054782f5d5e41f036c6d047d` ON `payload_header_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_header_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_44e10582d0695d751dd8863af3` ON `payload_footer_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b4bc21a5b982be6ea4316da69f` ON `payload_footer_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_footer_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_12e1aaa13157852ec040d44fec` ON `payload_news_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_04373df796d8c869634fda42bf` ON `payload_news_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_news_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_aeac0260f24c9356c440ec37dc` ON `payload_category_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_e3b4ccebf99452d9506bbb3438` ON `payload_category_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_category_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_368c961a32ec604103a99db0c5` ON `payload_author_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_fcdc26367b4c6fa7f61a98a814` ON `payload_author_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_author_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_6e87308875d21ed2b76baf0c2f` ON `payload_page_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b3bbc848ef0ab6a59d57793fda` ON `payload_page_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_page_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_3fe3cef26433b7827c7f3c5974` ON `payload_alert_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_8c635dd7568b752dae0fd1a49d` ON `payload_alert_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_alert_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_58d421ecd181f6ece23e7d676b` ON `payload_banner_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_35d3f295523cc2f879f533387f` ON `payload_banner_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_banner_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b642d94f965e09d9411d3c8295` ON `payload_document_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_d9b5cb9a6a8dfd2f1a34dd45cb` ON `payload_document_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_document_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_c6cdc1a4fb380731abe5f6802c` ON `payload_faq_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_326f1bf1e92331c97f1c42ff39` ON `payload_faq_channels_channel`", undefined);
        await queryRunner.query("DROP TABLE `payload_faq_channels_channel`", undefined);
        await queryRunner.query("DROP INDEX `IDX_1d6662206dad535369160daf8f` ON `payload_header`", undefined);
        await queryRunner.query("DROP TABLE `payload_header`", undefined);
        await queryRunner.query("DROP INDEX `IDX_fbfbba8b92b625313db5be7116` ON `payload_header_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_header_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_f97f617d406891e196f6ffa873` ON `payload_footer`", undefined);
        await queryRunner.query("DROP TABLE `payload_footer`", undefined);
        await queryRunner.query("DROP INDEX `IDX_c242286c5d7efe0fd5ab235fc9` ON `payload_footer_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_footer_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_news`", undefined);
        await queryRunner.query("DROP INDEX `IDX_7dd7a9ad57f2e3b60482f7e7f6` ON `payload_category`", undefined);
        await queryRunner.query("DROP TABLE `payload_category`", undefined);
        await queryRunner.query("DROP INDEX `IDX_85291b6b74fc27c1f5f145301f` ON `payload_author`", undefined);
        await queryRunner.query("DROP TABLE `payload_author`", undefined);
        await queryRunner.query("DROP INDEX `IDX_8210e9ea820cf46d548392930b` ON `payload_author_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_author_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_4e409ad46c6a1a22c2ed659f10` ON `payload_news_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_news_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_page`", undefined);
        await queryRunner.query("DROP TABLE `payload_page_block`", undefined);
        await queryRunner.query("DROP INDEX `IDX_761ff10fcefadc44d47f5cdead` ON `payload_page_block_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_page_block_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_54abda8eabc14ed1c03ea93b14` ON `payload_alert`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b9287046fbd7dd1988f2b1b6ee` ON `payload_alert`", undefined);
        await queryRunner.query("DROP TABLE `payload_alert`", undefined);
        await queryRunner.query("DROP INDEX `IDX_fc564aad49ec6a6017d53f8d23` ON `payload_alert_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_alert_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_c8d3ad5922da044ea3dedf6e5a` ON `payload_banner`", undefined);
        await queryRunner.query("DROP TABLE `payload_banner`", undefined);
        await queryRunner.query("DROP INDEX `IDX_31168764efeebfbc548f36a7c5` ON `payload_banner_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_banner_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_44be831306fca0206c4100be21` ON `payload_document`", undefined);
        await queryRunner.query("DROP TABLE `payload_document`", undefined);
        await queryRunner.query("DROP INDEX `IDX_408a04bf3650f8881e3ef0e491` ON `payload_document_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_document_translation`", undefined);
        await queryRunner.query("DROP INDEX `IDX_0fa62116e26c6f940b9b84fc23` ON `payload_faq`", undefined);
        await queryRunner.query("DROP TABLE `payload_faq`", undefined);
        await queryRunner.query("DROP INDEX `IDX_aa9a532bc59abd344cc0384b32` ON `payload_faq_translation`", undefined);
        await queryRunner.query("DROP TABLE `payload_faq_translation`", undefined);
   }

}
