import gql from 'graphql-tag';

const commonApiExtensions = gql`
    enum ReviewType {
        SELLER
        PRODUCT
        BOOKING
    }

    type Review implements Node {
        id: ID!
        type: ReviewType!
        productId: ID
        sellerId: ID
        bookingId: ID
        seller: Seller
        product: Product
        booking: Booking
        customer: Customer
        createdAt: DateTime!
        updatedAt: DateTime!
        comment: String
        rating: Float
        public: Boolean
    }

    type ReviewList implements PaginatedList {
        items: [Review!]!
        totalItems: Int!
        averageRating: Float
    }

    # auto-generated by Vendure
    input ReviewListOptions

    extend type Query {
        review(id: ID!): Review
        reviews(options: ReviewListOptions): ReviewList!
    }

    input CreateReviewInput {
        type: ReviewType!
        itemId: ID!
        sellerId: ID!
        comment: String
        rating: Float!
        public: Boolean
    }

    input UpdateReviewInput {
        id: ID!
        comment: String
        rating: Float
        public: Boolean
    }

    extend type Mutation {
        createReview(input: CreateReviewInput!): Review!
        updateReview(input: UpdateReviewInput!): Review!
        deleteReview(id: ID!): DeletionResponse!
        deleteReviews(ids: [ID!]): [DeletionResponse!]!
    }
`;

export const adminApiExtensions = gql`
    ${commonApiExtensions}
`;

export const shopApiExtensions = gql`
    ${commonApiExtensions}
`;
